default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db              # ← 非常に重要
  username: postgres    # ← docker-compose.ymlと合わせる
  password: password    # ← docker-compose.ymlと合わせる

development:
  <<: *default
  database: marathon_yarouze_development

test:
  <<: *default
  database: marathon_yarouze_test